"""
FAISS + BM25 hybrid retriever for the unmanned vending vehicle RAG project.

Input:  dataset/preprocessed/chunks.jsonl generated by rag_data_preprocessor.py
Output: FAISS index directory + metadata snapshot

Examples:
    python rag_vector_retriever.py build --chunks ./dataset/preprocessed/chunks.jsonl --index ./dataset/faiss_index
    python rag_vector_retriever.py search --index ./dataset/faiss_index --query "适合熬夜的饮料" --knowledge-type product
"""

from __future__ import annotations

import argparse
import json
import pickle
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

from langchain_core.documents import Document
from langchain_community.vectorstores import FAISS
from langchain_community.retrievers import BM25Retriever

try:
    from langchain_huggingface import HuggingFaceEmbeddings
except ImportError:  # pragma: no cover
    HuggingFaceEmbeddings = None


@dataclass
class SearchResult:
    rank: int
    score: float
    content: str
    metadata: Dict[str, Any]


class BGEFAISSHybridRetriever:
    """Vector + lexical hybrid retriever with metadata filtering."""

    def __init__(
        self,
        embedding_model: str = "BAAI/bge-small-zh-v1.5",
        device: str = "cpu",
        vector_top_k: int = 12,
        bm25_top_k: int = 12,
        rrf_k: int = 60,
    ):
        self.embedding_model = embedding_model
        self.device = device
        self.vector_top_k = vector_top_k
        self.bm25_top_k = bm25_top_k
        self.rrf_k = rrf_k
        self.embeddings = self._init_embeddings()
        self.vectorstore: Optional[FAISS] = None
        self.documents: List[Document] = []
        self.bm25_retriever: Optional[BM25Retriever] = None

    def _init_embeddings(self):
        if HuggingFaceEmbeddings is None:
            raise RuntimeError(
                "Missing dependency: langchain-huggingface. "
                "Install with: pip install langchain-huggingface sentence-transformers faiss-cpu rank_bm25"
            )
        return HuggingFaceEmbeddings(
            model_name=self.embedding_model,
            model_kwargs={"device": self.device},
            encode_kwargs={"normalize_embeddings": True},
        )

    def build_from_chunks(self, chunks_jsonl: Path) -> None:
        self.documents = self._load_chunks(chunks_jsonl)
        if not self.documents:
            raise ValueError(f"No chunks loaded from {chunks_jsonl}")
        self.vectorstore = FAISS.from_documents(self.documents, self.embeddings)
        self._build_bm25()

    def save(self, index_dir: Path) -> None:
        if self.vectorstore is None:
            raise ValueError("Build or load a FAISS index before saving.")
        index_dir.mkdir(parents=True, exist_ok=True)
        self.vectorstore.save_local(str(index_dir / "faiss"))
        with (index_dir / "documents.pkl").open("wb") as f:
            pickle.dump(self.documents, f)
        manifest = {
            "embedding_model": self.embedding_model,
            "document_count": len(self.documents),
            "vector_top_k": self.vector_top_k,
            "bm25_top_k": self.bm25_top_k,
            "rrf_k": self.rrf_k,
            "files": ["faiss", "documents.pkl", "manifest.json"],
        }
        (index_dir / "manifest.json").write_text(
            json.dumps(manifest, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )

    def load(self, index_dir: Path) -> None:
        self.vectorstore = FAISS.load_local(
            str(index_dir / "faiss"),
            self.embeddings,
            allow_dangerous_deserialization=True,
        )
        with (index_dir / "documents.pkl").open("rb") as f:
            self.documents = pickle.load(f)
        self._build_bm25()

    def search(
        self,
        query: str,
        top_k: int = 5,
        filters: Optional[Dict[str, Any]] = None,
    ) -> List[SearchResult]:
        if self.vectorstore is None or self.bm25_retriever is None:
            raise ValueError("Build or load index before searching.")

        candidate_multiplier = 4 if filters else 1
        vector_docs = self.vectorstore.similarity_search(
            query,
            k=max(self.vector_top_k, top_k * candidate_multiplier),
        )
        bm25_docs = self.bm25_retriever.invoke(query)[: max(self.bm25_top_k, top_k * candidate_multiplier)]

        fused = self._rrf_fusion(vector_docs, bm25_docs)
        filtered = [(doc, score) for doc, score in fused if self._metadata_match(doc.metadata, filters)]

        results: List[SearchResult] = []
        seen_parent_ids = set()
        for doc, score in filtered:
            parent_id = doc.metadata.get("parent_id") or doc.metadata.get("chunk_id")
            # Avoid flooding the final context with repeated chunks from the same source.
            if parent_id in seen_parent_ids and doc.metadata.get("knowledge_type") != "product":
                continue
            seen_parent_ids.add(parent_id)
            results.append(
                SearchResult(
                    rank=len(results) + 1,
                    score=score,
                    content=doc.page_content,
                    metadata={**doc.metadata, "rrf_score": score},
                )
            )
            if len(results) >= top_k:
                break
        return results

    def build_context(self, results: List[SearchResult], max_chars: int = 2400) -> str:
        parts: List[str] = []
        total = 0
        for item in results:
            meta = item.metadata
            header = (
                f"【检索结果{item.rank}】"
                f"类型:{meta.get('knowledge_type', 'unknown')} | "
                f"标题:{meta.get('title') or meta.get('product_name') or meta.get('section_title', '')} | "
                f"来源:{meta.get('source_path', '')}"
            )
            text = f"{header}\n{item.content.strip()}\n"
            if total + len(text) > max_chars:
                break
            parts.append(text)
            total += len(text)
        return "\n".join(parts)

    def _build_bm25(self) -> None:
        self.bm25_retriever = BM25Retriever.from_documents(self.documents)
        self.bm25_retriever.k = self.bm25_top_k

    def _load_chunks(self, chunks_jsonl: Path) -> List[Document]:
        docs: List[Document] = []
        with chunks_jsonl.open("r", encoding="utf-8") as f:
            for line in f:
                if not line.strip():
                    continue
                item = json.loads(line)
                metadata = dict(item.get("metadata") or {})
                for key in [
                    "chunk_id",
                    "parent_id",
                    "title",
                    "source_path",
                    "source_type",
                    "knowledge_type",
                    "chunk_index",
                ]:
                    if key in item:
                        metadata[key] = item[key]
                docs.append(Document(page_content=item["content"], metadata=metadata))
        return docs

    def _rrf_fusion(
        self,
        vector_docs: Iterable[Document],
        bm25_docs: Iterable[Document],
    ) -> List[Tuple[Document, float]]:
        scores: Dict[str, float] = {}
        objects: Dict[str, Document] = {}

        for docs in [list(vector_docs), list(bm25_docs)]:
            for rank, doc in enumerate(docs, start=1):
                doc_id = str(doc.metadata.get("chunk_id") or hash(doc.page_content))
                objects[doc_id] = doc
                scores[doc_id] = scores.get(doc_id, 0.0) + 1.0 / (self.rrf_k + rank)

        return [(objects[doc_id], score) for doc_id, score in sorted(scores.items(), key=lambda x: x[1], reverse=True)]

    def _metadata_match(self, metadata: Dict[str, Any], filters: Optional[Dict[str, Any]]) -> bool:
        if not filters:
            return True
        for key, expected in filters.items():
            actual = metadata.get(key)
            if expected is None or expected == "":
                continue
            if isinstance(expected, list):
                if actual not in expected:
                    return False
            elif isinstance(expected, dict):
                if not self._range_match(actual, expected):
                    return False
            else:
                if str(actual) != str(expected):
                    return False
        return True

    def _range_match(self, actual: Any, expected: Dict[str, Any]) -> bool:
        value = self._to_float(actual)
        if value is None:
            return False
        if "min" in expected and value < float(expected["min"]):
            return False
        if "max" in expected and value > float(expected["max"]):
            return False
        return True

    def _to_float(self, value: Any) -> Optional[float]:
        if value is None:
            return None
        if isinstance(value, (int, float)):
            return float(value)
        match = __import__("re").search(r"\d+(?:\.\d+)?", str(value))
        return float(match.group(0)) if match else None


def parse_filter_args(args: argparse.Namespace) -> Dict[str, Any]:
    filters: Dict[str, Any] = {}
    if getattr(args, "knowledge_type", None):
        filters["knowledge_type"] = args.knowledge_type
    if getattr(args, "category", None):
        filters["category"] = args.category
    if getattr(args, "max_price", None) is not None:
        filters["price"] = {"max": args.max_price}
    return filters


def build_command(args: argparse.Namespace) -> None:
    retriever = BGEFAISSHybridRetriever(
        embedding_model=args.embedding_model,
        device=args.device,
        vector_top_k=args.vector_top_k,
        bm25_top_k=args.bm25_top_k,
    )
    retriever.build_from_chunks(Path(args.chunks))
    retriever.save(Path(args.index))
    print(f"FAISS index built: {args.index}")


def search_command(args: argparse.Namespace) -> None:
    retriever = BGEFAISSHybridRetriever(
        embedding_model=args.embedding_model,
        device=args.device,
        vector_top_k=args.vector_top_k,
        bm25_top_k=args.bm25_top_k,
    )
    retriever.load(Path(args.index))
    results = retriever.search(args.query, top_k=args.top_k, filters=parse_filter_args(args))
    print(json.dumps([result.__dict__ for result in results], ensure_ascii=False, indent=2))


def main() -> None:
    parser = argparse.ArgumentParser(description="Build and query a FAISS + BM25 hybrid RAG index.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    build_parser = subparsers.add_parser("build")
    build_parser.add_argument("--chunks", default="./dataset/preprocessed/chunks.jsonl")
    build_parser.add_argument("--index", default="./dataset/faiss_index")
    build_parser.add_argument("--embedding-model", default="BAAI/bge-small-zh-v1.5")
    build_parser.add_argument("--device", default="cpu")
    build_parser.add_argument("--vector-top-k", type=int, default=12)
    build_parser.add_argument("--bm25-top-k", type=int, default=12)
    build_parser.set_defaults(func=build_command)

    search_parser = subparsers.add_parser("search")
    search_parser.add_argument("--index", default="./dataset/faiss_index")
    search_parser.add_argument("--query", required=True)
    search_parser.add_argument("--top-k", type=int, default=5)
    search_parser.add_argument("--knowledge-type", choices=["product", "school_history", "lab_profile", "general"])
    search_parser.add_argument("--category")
    search_parser.add_argument("--max-price", type=float)
    search_parser.add_argument("--embedding-model", default="BAAI/bge-small-zh-v1.5")
    search_parser.add_argument("--device", default="cpu")
    search_parser.add_argument("--vector-top-k", type=int, default=12)
    search_parser.add_argument("--bm25-top-k", type=int, default=12)
    search_parser.set_defaults(func=search_command)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()

